version: '3'

networks:
  Open-Source-Bazaar:

services:
  Animal-Rescue:
    image: Open-Source-Bazaar/Animal-Rescue
    networks:
      - Open-Source-Bazaar
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/ || exit 1']
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - 'autoheal=true'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 500M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  caddy:
    depends_on:
      - Animal-Rescue
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - Open-Source-Bazaar
    command: caddy reverse-proxy --from your.domain.com --to Animal-Rescue:3000
